### ISSUE TITLE
Support for module-level docs

### ISSUE THREAD

**Issue by maoe** [termoshtt/katexit#1]
Is there a way to make this crate work with module-level docs?

I've tried https://github.com/termoshtt/katexit/compare/main...maoe:module-level with no luck.

**Comment by termoshtt** [comment]
0.1.4 has been released, and it allows to use `#![katexit::katexit]` if compiled by nightly compiler. See #3 and https://github.com/termoshtt/katexit/blob/main/katexit-example-nightly/src/lib.rs for detail
